language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

install:
  - composer self-update && composer --version
  - composer install --prefer-dist --dev
  - wget https://scrutinizer-ci.com/ocular.phar

script:
  - vendor/bin/phpunit --verbose --coverage-clover=coverage.clover --configuration="phpunit.xml"
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
